### ISSUE TITLE
Using module name in buildModule

### ISSUE THREAD

**Issue by mrleblanc101** [daliborgogic/interpolation#3]
Why can't we use:
```
buildModules: [
  'nuxt3-interpolation' 
]
```
The readme says to use:
```
buildModules: [
  '~/node_modules/nuxt3-interpolation/index.cjs'
]
```
Which is odd

**Comment by daliborgogic** [comment]
@mrleblanc101 now we can. In that time there was a bug and that was a quick fix.

**Comment by mrleblanc101** [comment]
Good, thanks ! I'll close them

**Comment by mrleblanc101** [comment]
@daliborgogic might be worth updating the README to reflect that

**Comment by daliborgogic** [comment]
@mrleblanc101 fill free to PR. This time will be much faster to merge

**Comment by mrleblanc101** [comment]
#4

**Comment by mrleblanc101** [comment]
Aslo, isn't the repo name being only "interpolation" confusing ? It doesn't really hint that it's a nuxt module. Why not `nuxt3-interpolation` like the npm package name ? Or use the same repo as `nuxt-interpolation` (for nuxt2) on 2 separate branch (main for Nuxt 3 and a `nuxt-2` branch) ?
